export const NOVA_PESTANA = "NOVA_PESTANA";
export const TAB_SELECCIONADA = "TAB_SELECCIONADA";
export const BORRAR_PESTANA = "BORRAR_PESTANA";
export const ACTUALIZAR_TAB_ID = "ACTUALIZAR_TAB_ID";
export const ACTUALIZAR_TABS_INFO = "ACTUALIZAR_TABS_INFO";
