export const FINALIZAR_SESION_GLPI = "FINALIZAR_SESION";
export const RECUPERAR_SESION = "RECUPERAR_SESION";
export const INICIAR_SESION_GLPI = "INICIAR_SESION_GLPI";
export const OBTER_INCIDENCIAS_GLPI = "OBTER_INCIDENCIAS_GLPI";
