export const INICIAR_SESION = "INICIAR_SESION";
export const FINALIZAR_SESION = "FINALIZAR_SESION";
export const RECUPERAR_SESION = "RECUPERAR_SESION";
export const INICIAR_SESION_GLPI = "INICIAR_SESION_GLPI";
